version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/app
permissions:
   - object: /home/ubuntu/app
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
  AfterInstall:
    - location: scripts/install_laravel
      timeout: 300
      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root

