version: 0.2
env:
  variables:
    APP_NAME: "Millonarios FC - CodePipeline CI/CD"
phases:
 pre_build:
   commands:
     - php -m
     - php --ini
 build:
   commands:
     - rm -rf vendor
     - rm -rf composer.lock
     - composer install --no-interaction --prefer-dist
     - composer dump-autoload
     - touch database/database.sqlite
 post_build:
   commands:
     - vendor/bin/parallel-lint --exclude vendor .
     - php artisan migrate:fresh --path=database/migrations/2way --database=sqlite --force --seed
     - vendor/bin/codecept run functional
 #eb_codebuild_settings:
 #  CodeBuildServiceRole: s3-admin-access
 #  ComputeType: BUILD_GENERAL1_SMALL
 #  Image: aws/codebuild/docker:17.09.0
 #  Timeout: 60
