version: 0.2
env:
  variables:
    APP_NAME: "Millonarios FC - CodePipeline CI/CD"
    DB_CONNECTION: "mysql"
    DB_HOST: "awsfcf2waysports.co6n6hotu5cp.us-east-1.rds.amazonaws.com"
    DB_PORT: "3306"
    DB_DATABASE: "millonarios_develop"
    DB_USERNAME: "shok-millonarios"
  parameter-store:
    DB_PASSWORD: "keyforRDS"
phases:
 pre_build:
   commands:
     - php -m
     - php --ini
     - rm -rf vendor
     - rm -rf composer.lock
     - echo ************************************************************************************************
     - echo ************************************  MYSQL INSTALL ********************************************
     - echo ************************************************************************************************
     - apt-get install mysql-server php-mysql -y
 build:
   commands:
     - composer install --no-interaction --prefer-dist
     - composer dump-autoload
     - touch database/database.sqlite
 post_build:
   commands:
     - vendor/bin/parallel-lint --exclude vendor .
     - php artisan migrate:fresh --path=database/migrations/2way --database=sqlite --force --seed
     #- php artisan migrate --path=/database/migrations/v3 --database=sqlite --force
     #- php artisan migrate --path=/database/migrations/v4 --database=sqlite --force
     #- php artisan migrate --path=/database/migrations/v5 --database=sqlite --force
     - echo ************************************************************************************************
     - echo ****************  MIGRATE FOR DATABASE ON RDS FOR millonarios_develop **************************
     - echo ************************************************************************************************
     #- php artisan migrate --path=/database/migrations/v3 --database=mysql --force
     #- php artisan migrate --path=/database/migrations/v4 --database=mysql --force
     #- php artisan migrate --path=/database/migrations/v5 --database=mysql --force
     - echo ************************************************************************************************
     - echo ****************  MIGRATE FOR DATABASE ON RDS FOR millonarios_develop **************************
     - echo ************************************************************************************************
     - vendor/bin/codecept run functional
 #eb_codebuild_settings:
 #  CodeBuildServiceRole: s3-admin-access
 #  ComputeType: BUILD_GENERAL1_SMALL
 #  Image: aws/codebuild/docker:17.09.0
 #  Timeout: 60
