branch-defaults:
  devssl:
    environment: millonarios-dev
  master:
    environment: prod-env
  staging:
    environment: stg-env
  stgssl:
    environment: millonarios-stg
environment-defaults:
  dev-env:
    branch: dev
    repository: millonarios_backend
  millonarios-dev:
    branch: devssl
    repository: millonarios_backend
global:
  application_name: millonarios
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 7.1 running on
    64bit Amazon Linux/2.6.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
