branch-defaults:
  dev:
    environment: dev-env
  master:
    environment: prod-env
environment-defaults:
  dev-env:
    branch: master
    repository: millonarios_backend
global:
  application_name: millonarios
  default_ec2_keyname: barcelonasc
  default_platform: arn:aws:elasticbeanstalk:sa-east-1::platform/PHP 7.0 running on
    64bit Amazon Linux/2.5.0
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
