
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Profanity Filter Configuration
    |--------------------------------------------------------------------------
    |
    |
    */

    /* Disable to replace partial words. */
    'replaceFullWords' => true,

    /* Replace bad words with this, based on length of word */
    'replaceWith' => '*',

    /* Replace related letters */
    'strReplace' => [
            'a' => '(a|a\.|a\-|4|@|Á|á|À|Â|à|Â|â|Ä|ä|Ã|ã|Å|å|α|Δ|Λ|λ)',
            'b' => '(b|b\.|b\-|8|\|3|ß|Β|β)',
            'c' => '(c|c\.|c\-|Ç|ç|¢|€|<|\(|{|©)',
            'd' => '(d|d\.|d\-|&part;|\|\)|Þ|þ|Ð|ð)',
            'e' => '(e|e\.|e\-|3|€|È|è|É|é|Ê|ê|∑)',
            'f' => '(f|f\.|f\-|ƒ)',
            'g' => '(g|g\.|g\-|6|9)',
            'h' => '(h|h\.|h\-|Η)',
            'i' => '(i|i\.|i\-|!|\||\]\[|]|1|∫|Ì|Í|Î|Ï|ì|í|î|ï)',
            'j' => '(j|j\.|j\-)',
            'k' => '(k|k\.|k\-|Κ|κ)',
            'l' => '(l|1\.|l\-|!|\||\]\[|]|£|∫|Ì|Í|Î|Ï)',
            'm' => '(m|m\.|m\-)',
            'n' => '(n|n\.|n\-|η|Ν|Π)',
            'o' => '(o|o\.|o\-|0|Ο|ο|Φ|¤|°|ø)',
            'p' => '(p|p\.|p\-|ρ|Ρ|¶|þ)',
            'q' => '(q|q\.|q\-)',
            'r' => '(r|r\.|r\-|®)',
            's' => '(s|s\.|s\-|5|\$|§)',
            't' => '(t|t\.|t\-|Τ|τ)',
            'u' => '(u|u\.|u\-|υ|µ)',
            'v' => '(v|v\.|v\-|υ|ν)',
            'w' => '(w|w\.|w\-|ω|ψ|Ψ)',
            'x' => '(x|x\.|x\-|Χ|χ)',
            'y' => '(y|y\.|y\-|¥|γ|ÿ|ý|Ÿ|Ý)',
            'z' => '(z|z\.|z\-|Ζ)',
    ],

    /* Replace these words no matter what language. */
    'defaults' => [
        'fuck',
        'shit',
        'mierda',
        'coño',
        'maldito',
        'maldita',
        'puta',
        'puto',
        'malparido',
        'gonorrea',
        'hpta',
        'gonorzofia',
        'hijueputta',
        'hp',
        'marica',
        'mk',
        'mca',
        'gurrupleta',
        'pinche',
        'pichurria',
        'maricon',
        'guevon',
        'huevon',
        'garbimba',
        'monda',
        'fufa',
        'fufo',
        'fufurufa',
        'fufurufo',
        'coscorria',
        'pamplemusa',
        'pamplemuso',
        'garnupia',
        'cule',
        'chunchurria',
        'chucha',
        'percanta',
        'verga',
        'seborrea',
        'pirobo',
        'cebo',
        'chimba',
        'pene',
        'vagina',
        'cucha',
        'chocha',
        'chocho',
        'pinga',
        'poronga',
        'pendejo',
        'concha',
        'bitch',
        'pussy',
        'dick',
        'silly',
        'perro',
        'perra',
        'zorro',
        'zorra',
        'casquivana',
        'culo',
        'corota',
        'jopo',
        'culiar',
        'culero',
        'marica',
        'culear',
        'mierdero',
        'cuca',
        'golfa',
        'rata',
        'gueva',
        'wuevon',
        'guache',
        'care pito',
        'pito',
        'picha',
        'zunga',
        'guebo',
        'bobo',
        'imbecil',
        'imbesil',
        'estupido',
        'bruto',
        'idiota',
        'culiao',
        'bandida',
        'chandoso',
        'buscona',
        'garulla',
        'sifilitico'
    ],
];
